#! /bin/sh

# This script provides Slack notifications.
# Be sure to change the Slack URL to the actual Webhook URL.

# First arg is "true" or "false", this is the "failed" check value.
# The second one contains check's name.
# The third one is the error description.

case $1 in
    "true")
        data="{\"attachments\": [{\"text\": \"Failed: $2\", \"color\": \"danger\"}, {\"color\": \"warning\", \"text\": \"$3\"}]}"
        ;;
    "false")
        data="{\"attachments\": [{\"text\": \"Fixed: $2\", \"color\": \"good\"}]}"
        ;;
    *)
        exit 1
        ;;
esac

curl -sSH "Content-Type:application/json" -d "$data" https://hooks.slack.com/services/INTEGRATION_PATH
